

// Theming scripts. This file is generated by (org.pentaho.platform.web.servlet.ThemeServlet) and cannot be found on disk
var active_theme = "ruby";

var core_theme_tree = {"sample1":{"rootDir":"content/common-ui/resources/themes/sample1/","resources":["style1.css"]},"native":{"rootDir":"content/common-ui/resources/themes/native/","resources":["globalNative.css"]},"crystal":{"rootDir":"content/common-ui/resources/themes/crystal/","resources":["globalCrystal.css","bootstrap/css/bootstrap-namespaced.css"]},"replaceable":{"rootDir":"content/common-ui/resources/themes/replaceable/","resources":["replaceable.css"]},"onyx":{"rootDir":"content/common-ui/resources/themes/onyx/","resources":["globalOnyx.css","bootstrap/css/bootstrap-namespaced.css"]},"slate":{"rootDir":"content/common-ui/resources/themes/slate/","resources":["globalSlate.css"]},"sapphire":{"rootDir":"content/common-ui/resources/themes/sapphire/","resources":["globalSapphire.css","bootstrap/css/bootstrap-namespaced.css"]},"ruby":{"rootDir":"content/common-ui/resources/themes/ruby/","resources":["globalRuby.css","bootstrap/css/bootstrap-namespaced.css"]}};

// Inject the theme script to handle the insertion of requested theme resources

var module_theme_tree = {"det":{"rootDir":"content/analyzer/styles/themes/det/","resources":["anaDet.css"]},"crystal":{"rootDir":"content/analyzer/styles/themes/crystal/","resources":["anaCrystal.css"]},"onyx":{"rootDir":"content/analyzer/styles/themes/onyx/","resources":["anaOnyx.css"]},"slate":{"rootDir":"content/analyzer/styles/themes/slate/","resources":["anaSlate.css"]},"sapphire":{"rootDir":"content/analyzer/styles/themes/sapphire/","resources":["anaSapphire.css"]},"ruby":{"rootDir":"content/analyzer/styles/themes/ruby/","resources":["anaRuby.css"]}};

(function() {
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = CONTEXT_PATH + 'js/themeResources.js';
var existing = document.getElementsByTagName('script')[0];
existing.parentNode.insertBefore(script, existing);
}());