

// Theming scripts. This file is generated by (org.pentaho.platform.web.servlet.ThemeServlet) and cannot be found on disk
var active_theme = "ruby";

var core_theme_tree = {"sample1":{"rootDir":"content/common-ui/resources/themes/sample1/","resources":["style1.css"]},"native":{"rootDir":"content/common-ui/resources/themes/native/","resources":["globalNative.css"]},"crystal":{"rootDir":"content/common-ui/resources/themes/crystal/","resources":["globalCrystal.css","bootstrap/css/bootstrap-namespaced.css"]},"replaceable":{"rootDir":"content/common-ui/resources/themes/replaceable/","resources":["replaceable.css"]},"onyx":{"rootDir":"content/common-ui/resources/themes/onyx/","resources":["globalOnyx.css","bootstrap/css/bootstrap-namespaced.css"]},"slate":{"rootDir":"content/common-ui/resources/themes/slate/","resources":["globalSlate.css"]},"sapphire":{"rootDir":"content/common-ui/resources/themes/sapphire/","resources":["globalSapphire.css","bootstrap/css/bootstrap-namespaced.css"]},"ruby":{"rootDir":"content/common-ui/resources/themes/ruby/","resources":["globalRuby.css","bootstrap/css/bootstrap-namespaced.css"]}};

// Inject the theme script to handle the insertion of requested theme resources

var module_theme_tree = {"crystal":{"rootDir":"content/reporting/reportviewer/themes/crystal/","resources":["Crystal.css"]},"onyx":{"rootDir":"content/reporting/reportviewer/themes/onyx/","resources":["Onyx.css"]},"slate":{"rootDir":"content/reporting/reportviewer/themes/slate/","resources":["Slate.css"]},"sapphire":{"rootDir":"content/reporting/reportviewer/themes/sapphire/","resources":["Sapphire.css"]},"ruby":{"rootDir":"content/reporting/reportviewer/themes/ruby/","resources":["Ruby.css"]}};

(function() {
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = CONTEXT_PATH + 'js/themeResources.js';
var existing = document.getElementsByTagName('script')[0];
existing.parentNode.insertBefore(script, existing);
}());